# values.yaml
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent # Image pull policy (e.g., Always, IfNotPresent)

replicaCount: 1          # Number of replicas (pods) to run
service:
  type: ClusterIP        # Service type (ClusterIP, NodePort, LoadBalancer)
  port: 80               # Port for the service