# values.yaml
image:
  repository: httpd
  tag: latest
  pullPolicy: IfNotPresent # Image pull policy (e.g., Always, IfNotPresent)

replicaCount: 1          # Number of replicas (pods) to run
service:
  type: NodePort        # Service type (ClusterIP, NodePort, LoadBalancer)
  port: 80               # Port for the service
  nodePort: 30001